// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhCVcVU5xiX9x-8mJfeGTxQU_g8lH67_k',
    appId: '1:597577797414:web:b17d8dd3cc966b2acf3be7',
    messagingSenderId: '597577797414',
    projectId: 'kigali-city-directory-2eb11',
    authDomain: 'kigali-city-directory-2eb11.firebaseapp.com',
    storageBucket: 'kigali-city-directory-2eb11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPdeE8aEeDJH9Vm5Pp4Mh8LwV0eUqOLm0',
    appId: '1:597577797414:android:cb61357885e04e21cf3be7',
    messagingSenderId: '597577797414',
    projectId: 'kigali-city-directory-2eb11',
    storageBucket: 'kigali-city-directory-2eb11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAF_j6t6svAffH8oynmxJTASJZAp8U1wA',
    appId: '1:597577797414:ios:bf439dc9fb8b5902cf3be7',
    messagingSenderId: '597577797414',
    projectId: 'kigali-city-directory-2eb11',
    storageBucket: 'kigali-city-directory-2eb11.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityDirectory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAF_j6t6svAffH8oynmxJTASJZAp8U1wA',
    appId: '1:597577797414:ios:bf439dc9fb8b5902cf3be7',
    messagingSenderId: '597577797414',
    projectId: 'kigali-city-directory-2eb11',
    storageBucket: 'kigali-city-directory-2eb11.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityDirectory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhCVcVU5xiX9x-8mJfeGTxQU_g8lH67_k',
    appId: '1:597577797414:web:66706337167e099acf3be7',
    messagingSenderId: '597577797414',
    projectId: 'kigali-city-directory-2eb11',
    authDomain: 'kigali-city-directory-2eb11.firebaseapp.com',
    storageBucket: 'kigali-city-directory-2eb11.firebasestorage.app',
  );
}
